In [10]:
import numpy as np
from numpy import linalg

In [11]:
np.array([1,2,3,4,5,6,7,8,9],int)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.array(["a","b","c","d","e","f","g","h","i"],str)

array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], dtype='<U1')

In [13]:
np.array(["Python","C++","C","JAVA","JS"],str)

array(['Python', 'C++', 'C', 'JAVA', 'JS'], dtype='<U6')

In [14]:
np.array([1.,2.7,3.0,4.1,5.9,6.2,70.0,81.1,90.0],float)

array([ 1. ,  2.7,  3. ,  4.1,  5.9,  6.2, 70. , 81.1, 90. ])

In [44]:
m = np.array([[1,2,3],[1,4,9],[1,8,27]])
m

array([[ 1,  2,  3],
       [ 1,  4,  9],
       [ 1,  8, 27]])

In [45]:
m.T #Transpose

array([[ 1,  1,  1],
       [ 2,  4,  8],
       [ 3,  9, 27]])

In [51]:
linalg.eig(m) #-> eigen values

(array([29.94276746,  0.21788396,  1.83934857]),
 array([[-0.11984233, -0.84842319, -0.71625223],
        [-0.32951272,  0.51502827, -0.65631136],
        [-0.93651438, -0.12216372,  0.23714581]]))

In [52]:
linalg.inv(m) #-> inverse of a matrix

array([[ 3.        , -2.5       ,  0.5       ],
       [-1.5       ,  2.        , -0.5       ],
       [ 0.33333333, -0.5       ,  0.16666667]])

In [54]:
linalg.det(m) #-> determinant of a matrix

12.0

In [57]:
a = m.flatten()
a

array([ 1,  2,  3,  1,  4,  9,  1,  8, 27])

In [58]:
m.ravel()

array([ 1,  2,  3,  1,  4,  9,  1,  8, 27])

# Difference between ravel and flatter

## ravel():
* return only reference/view of original array/matrix
* If we modify an array/matrix, then the value of original array/matrix also changes
* ravel is faster than the flatten because its doesn't occupy any space in the memory
* ravel is library-level function

## flatten():
* return copy of original array/matrix
* if we modify the original array/matrix, then the value of original array/matrix will not change
* flatten is slower than the flatten because its occupy the space in the memory
* flatten is a method of an ndarray object

In [69]:
x = np.matrix([[1,2],[3,4]])
y = np.matrix([[1,4],[9,16]])

In [70]:
np.dot(x,y)

matrix([[19, 36],
        [39, 76]])